export { getParity } from './getParity'
export { getSign } from './getSign'
export { getNumberType } from './getNumberType'
export { isInRange } from './isInRange'
export { shortenNumber } from './shortenNumber'